// <auto-generated />
using System;
using DawwerOS.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DawwerOS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913200827_AddCategoryEntity")]
    partial class AddCategoryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DawwerOS.DAL.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_categories_is_active");

                    b.HasIndex("ParentCategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_parent_category_id_name");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Computers, smartphones, accessories, and electronic appliances.",
                            DisplayOrder = 1,
                            IconUrl = "/icons/categories/electronics.svg",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Everyday food items, beverages, fresh produce, and pantry staples.",
                            DisplayOrder = 2,
                            IconUrl = "/icons/categories/groceries.svg",
                            IsActive = true,
                            Name = "Groceries & Food"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing, shoes, watches, and fashion accessories.",
                            DisplayOrder = 3,
                            IconUrl = "/icons/categories/fashion.svg",
                            IsActive = true,
                            Name = "Fashion & Apparel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cookware, home decor, furniture, and kitchen essentials.",
                            DisplayOrder = 4,
                            IconUrl = "/icons/categories/home.svg",
                            IsActive = true,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal care, cosmetics, vitamins, and wellness products.",
                            DisplayOrder = 5,
                            IconUrl = "/icons/categories/health.svg",
                            IsActive = true,
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sporting equipment, fitness gear, and outdoor activity items.",
                            DisplayOrder = 6,
                            IconUrl = "/icons/categories/sports.svg",
                            IsActive = true,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobile phones, tablets, and wearable accessories.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Smartphones & Tablets",
                            ParentCategoryId = new Guid("00000000-0000-0000-0004-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal computers, laptops, monitors, and peripherals.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Laptops & Computers",
                            ParentCategoryId = new Guid("00000000-0000-0000-0004-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000021"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fruits, vegetables, and fresh herbs.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Fresh Produce",
                            ParentCategoryId = new Guid("00000000-0000-0000-0004-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000022"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Water, juices, soft drinks, tea, and coffee.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Beverages & Drinks",
                            ParentCategoryId = new Guid("00000000-0000-0000-0004-000000000002")
                        });
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.RevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jti");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_revoked_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_revoked_tokens_expires_at");

                    b.HasIndex("Jti")
                        .IsUnique()
                        .HasDatabaseName("ix_revoked_tokens_jti");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_revoked_tokens_user_id");

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CommercialRegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("commercial_registration_number");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("InformationRequestMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("information_request_message");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("suspension_reason");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_stores");

                    b.HasIndex("CommercialRegistrationNumber")
                        .HasDatabaseName("ix_stores_commercial_registration_number");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_stores_owner_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_stores_status");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("ix_stores_verification_status");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_store_documents");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_store_documents_store_id");

                    b.ToTable("store_documents", (string)null);
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StorePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_store_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_store_permissions_code");

                    b.ToTable("store_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Category = "Products",
                            Code = "Products.View",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View catalog products and product details.",
                            Name = "View Products"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Category = "Products",
                            Code = "Products.Manage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create, edit, and deactivate store products and categories.",
                            Name = "Manage Products"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Category = "Inventory",
                            Code = "Inventory.View",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View store stock levels and inventory availability.",
                            Name = "View Inventory"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Category = "Inventory",
                            Code = "Inventory.Manage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjust stock levels, restock items, and set availability thresholds.",
                            Name = "Manage Inventory"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Category = "Orders",
                            Code = "Orders.View",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View customer pickup reservations and order history.",
                            Name = "View Orders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            Category = "Orders",
                            Code = "Orders.Manage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Process orders, accept/reject reservations, and update fulfillment states.",
                            Name = "Manage Orders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            Category = "Staff",
                            Code = "Staff.Manage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add, update, suspend, and remove store staff accounts and assign roles.",
                            Name = "Manage Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            Category = "Store",
                            Code = "Store.Manage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage store settings, operating hours, and general configuration.",
                            Name = "Manage Store"
                        });
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_store_roles");

                    b.HasIndex("StoreId", "Name")
                        .HasDatabaseName("ix_store_roles_store_id_name");

                    b.ToTable("store_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full operational and administrative store management access.",
                            IsSystemRole = true,
                            Name = "Store Manager"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages catalog, inventory, and customer reservations.",
                            IsSystemRole = true,
                            Name = "Store Supervisor"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Maintains store stock and catalog entries.",
                            IsSystemRole = true,
                            Name = "Inventory Clerk"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handles pickup orders, customer checkouts, and inventory views.",
                            IsSystemRole = true,
                            Name = "Cashier"
                        });
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("StorePermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_permission_id");

                    b.Property<Guid>("StoreRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_store_role_permissions");

                    b.HasIndex("StorePermissionId")
                        .HasDatabaseName("ix_store_role_permissions_store_permission_id");

                    b.HasIndex("StoreRoleId", "StorePermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_role_permissions_store_role_id_store_permission_id");

                    b.ToTable("store_role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000001"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000002"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000003"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000004"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0001-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000005"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0001-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000006"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0001-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000007"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0001-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000008"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0002-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000001"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0002-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000002"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0002-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000003"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0002-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000004"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0002-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000005"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0002-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000006"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0003-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000001"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0003-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000002"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0003-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000003"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0003-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000004"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0004-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000001"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0004-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000003"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0004-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000005"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0003-0004-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StorePermissionId = new Guid("00000000-0000-0000-0001-000000000006"),
                            StoreRoleId = new Guid("00000000-0000-0000-0002-000000000004")
                        });
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("StoreRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_store_staff");

                    b.HasIndex("AssignedById")
                        .HasDatabaseName("ix_store_staff_assigned_by_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_store_staff_status");

                    b.HasIndex("StoreRoleId")
                        .HasDatabaseName("ix_store_staff_store_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_store_staff_user_id");

                    b.HasIndex("StoreId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_staff_store_id_user_id");

                    b.ToTable("store_staff", (string)null);
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreStaffPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_granted");

                    b.Property<Guid>("StorePermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_permission_id");

                    b.Property<Guid>("StoreStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_staff_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_store_staff_permissions");

                    b.HasIndex("StorePermissionId")
                        .HasDatabaseName("ix_store_staff_permissions_store_permission_id");

                    b.HasIndex("StoreStaffId", "StorePermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_staff_permissions_store_staff_id_store_permission_id");

                    b.ToTable("store_staff_permissions", (string)null);
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsPhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_phone_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_verified_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number")
                        .HasFilter("phone_number IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_verification_codes");

                    b.HasIndex("UserId", "Code", "Type")
                        .HasDatabaseName("ix_verification_codes_user_id_code_type");

                    b.ToTable("verification_codes", (string)null);
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.Category", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.RevokedToken", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.User", "User")
                        .WithMany("RevokedTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revoked_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.Store", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.User", "Owner")
                        .WithMany("OwnedStores")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stores_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreDocument", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.Store", "Store")
                        .WithMany("Documents")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_documents_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreRole", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.Store", "Store")
                        .WithMany("CustomRoles")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_store_roles_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreRolePermission", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.StorePermission", "StorePermission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("StorePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_role_permissions_store_permissions_store_permission_id");

                    b.HasOne("DawwerOS.DAL.Entities.StoreRole", "StoreRole")
                        .WithMany("RolePermissions")
                        .HasForeignKey("StoreRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_role_permissions_store_roles_store_role_id");

                    b.Navigation("StorePermission");

                    b.Navigation("StoreRole");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreStaff", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_store_staff_users_assigned_by_id");

                    b.HasOne("DawwerOS.DAL.Entities.Store", "Store")
                        .WithMany("StaffMembers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_staff_stores_store_id");

                    b.HasOne("DawwerOS.DAL.Entities.StoreRole", "StoreRole")
                        .WithMany("StaffMembers")
                        .HasForeignKey("StoreRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_staff_store_roles_store_role_id");

                    b.HasOne("DawwerOS.DAL.Entities.User", "User")
                        .WithMany("StoreAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_staff_users_user_id");

                    b.Navigation("AssignedBy");

                    b.Navigation("Store");

                    b.Navigation("StoreRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreStaffPermission", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.StorePermission", "StorePermission")
                        .WithMany("StaffPermissions")
                        .HasForeignKey("StorePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_staff_permissions_store_permissions_store_permission_");

                    b.HasOne("DawwerOS.DAL.Entities.StoreStaff", "StoreStaff")
                        .WithMany("CustomPermissions")
                        .HasForeignKey("StoreStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_staff_permissions_store_staff_members_store_staff_id");

                    b.Navigation("StorePermission");

                    b.Navigation("StoreStaff");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.VerificationCode", b =>
                {
                    b.HasOne("DawwerOS.DAL.Entities.User", "User")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_codes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.Store", b =>
                {
                    b.Navigation("CustomRoles");

                    b.Navigation("Documents");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StorePermission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("StaffPermissions");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.StoreStaff", b =>
                {
                    b.Navigation("CustomPermissions");
                });

            modelBuilder.Entity("DawwerOS.DAL.Entities.User", b =>
                {
                    b.Navigation("OwnedStores");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RevokedTokens");

                    b.Navigation("StoreAssignments");

                    b.Navigation("VerificationCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
